### ISSUE TITLE
Setting the default document

### ISSUE THREAD

**Issue by spuder** [opscode-cookbooks/iis#138]
The readme.md doesn't specify if this cookbook can set the default document for an application. 

Can it alter the default document? If so, I'd like to figure out how, and add it to the readme.

**Comment by EasyAsABC123** [comment]
@spuder This cookbook currently doesn't allow for the editing of the default document.  This is possible via the iis_config provider but won't be idempotent.  This should likely be rolled into a larger change of adding all the properties of sites/applications so that it can handle all the desires someone might have.

I'll look into this one immediately and add a pull request for it.

**Comment by EasyAsABC123** [comment]
This can be done fairly easily, but the real question this brought to my mind is...Do we want an `iis_root` to edit the iis root/Computer settings rather than a site or application.

In the meantime I can happily add it to iis_site and iis_pool, but I think this brings to light that we should have an `iis_root` and likely the `library/helper.rb` should contain some appcmd's that do `root`, `site`, and `pool`.

```
C:\Windows\System32\inetsrv>appcmd.exe set config "Default Web Site" /section:defaultDocument /enabled:true /+files.[value='home.html']
Applied configuration changes to section "system.webServer/defaultDocument" for
"MACHINE/WEBROOT/APPHOST/Default Web Site" at configuration commit path "MACHINE/WEBROOT/APPHOST/Default Web Site"

C:\Windows\System32\inetsrv>appcmd.exe set config "Default Web Site" /section:defaultDocument /enabled:true /-files
Applied configuration changes to section "system.webServer/defaultDocument" for "MACHINE/WEBROOT/APPHOST/Default Web Site" at configuration commit path "MACHINE/WEBROOT/APPHOST/Default Web Site"

C:\Windows\System32\inetsrv>appcmd.exe set config /section:defaultDocument /enabled:true /-files
Applied configuration changes to section "system.webServer/defaultDocument" for
"MACHINE/WEBROOT/APPHOST" at configuration commit path "MACHINE/WEBROOT/APPHOST"
```

**Comment by spuder** [comment]
Thanks for responding. 

I'm linux admin by trade who had never touched an IIS server until recently. I can't say what the best option would be. 

I am trying to do a wrapper cookbook to add a default document to an application. 
(I'm also interested in removing the defaults like index.htm, ).

**Comment by EasyAsABC123** [comment]
@spuder unfortunately the defaults like `index.htm` are defined at the root level not at the site/application level.

Everything below that is inherited by default.

**Comment by spuder** [comment]
On the web servers that I inherited, all default documents have been removed and replaced with a specific one. I think that is how I want to setup new web servers.

**Comment by EasyAsABC123** [comment]
@ksubrama want to have a google hangout to discuss this?

**Comment by ksubrama** [comment]
@EasyAsABC123 Yes I think we would need to discuss strategy on this.  Let me ping you offline in the next day or so.

**Comment by EasyAsABC123** [comment]
@ksubrama sounds good, definitely need to decide as I know we are working toward an iis@3.X.X release.  Adding this functionality or refactoring for an `iis_root` provider definitely is going to require more testing.

**Comment by ksubrama** [comment]
@EasyAsABC123 Hey..  sorry I didn't get back last week.  Life and thermodynamics and some cracked sprinkler pipes got in the way.  I'll try to catch up as quickly as I can.

**Comment by EasyAsABC123** [comment]
@ksubrama sounds good let me know when you want to do a google hangout and discuss this.

**Comment by EasyAsABC123** [comment]
@ksubrama as a sidenote i'll be at chefconf if you won't have time until then.

**Comment by EasyAsABC123** [comment]
@spuder if you have a moment can you please test https://github.com/opscode-cookbooks/iis/tree/enhancement-iis_root_provider it has a new provider called `iis_root` in that provider you can do something like...

```ruby
iis_root 'this doesn't do anything right now' do
  default_documents ['document_name1.extension', 'default.php']
end
```

This should delete all default documents from the root that aren't in the above array and add all that are in the array.  Please note this is untested code (can't test this second).

**Comment by spuder** [comment]
Thanks, I'm trying to test this now, but its been a few weeks since I've spun up vagrant and now It isn't working. 

http://stackoverflow.com/questions/30110585/vagrant-chef-solo-add-to-runlist

I'll report back once I figure this out.

**Comment by ksubrama** [comment]
I'm actually currently shaving that very yak.  I wanted to do a release today but apparently if you leave test-kitchen alone for 2 months, everything changes underneath you.

I'm now following http://kitchen.ci/blog/test-kitchen-windows-test-flight-with-vagrant/ but that has issues itself (the 2012R2 eval iso urls don't seem to download eval isos).  I'll be back when the yaks feel sufficiently shaved.

**Comment by EasyAsABC123** [comment]
@ksubrama coders be coders :) changing everything is the goal.  This branch will hopefully grow this weekend into a rich enhancement

**Comment by ksubrama** [comment]
I have https://github.com/ksubrama/windows/tree/ksubrama/win2012r2 to work around issues I had with cutting my own box.  Once I did cut that box, the instructions from the blog post above seemed to help and kitchen vagrant ran cleanly.

bundle update
bundle exec kitchen verify

That should now work.  If you have vagrant-wrapper from an old installation, you might want to gem uninstall that (it caused me some issues because it appeared earlier in the load path than the latest vagrant binaries).

**Comment by EasyAsABC123** [comment]
@ksubrama  thanks for that! fixing some bugs in this branch right now. :+1:

**Comment by spuder** [comment]
Been working on testing this all weekend. I still can't get test kitchen working on windows. The converge says it ran, yet no cookbooks were applied. 

I created a windows box based on the blog mentioned earlier and this repo
https://github.com/ksubrama/windows/tree/ksubrama/win2012r2

Then add the box

     vagrant box add spencer/windows-2012r2 ./box/virtualbox/eval-win2012r2-standard-nocm-1.0.4.box 

@ksubrama Would you be willing to look at my .kitchen.yml file? I'm at a loss for what is wrong. 

https://gist.github.com/spuder/f484043415b5af6ac247

**Comment by EasyAsABC123** [comment]
@spuder I know it was working like 2 commits ago, but now i don't know for sure since i've been refactoring and making functional code blocks to prepare for applications and sites.

**Comment by spuder** [comment]
I'm having a higher level problem. I can't get any cookbook to converge on windows. I think it is a problem with my .kitchen.yml or vagrant file. Do you have one you could share?

**Comment by spuder** [comment]
I've resolved the issue with vagrant, but I'm not able to get this to work. I've updated my berks file to point to the enhancement-iis_root_provider branch 

    cookbook 'iis', git: 'https://github.com/opscode-cookbooks/iis.git', branch: "enhancement-iis_root_provider"

```
==> default:   C:/opscode/chef/bin/chef-solo:23:in `load'
==> default:   C:/opscode/chef/bin/chef-solo:23:in `<main>'
==> default:
==> default: Relevant File Content:
==> default: ----------------------
==> default: C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/dsl/recipe.rb:
==> default:
==> default:  39:          elsif have_resource_class_for?(method_symbol)
==> default:  40:            # Otherwise, we're rocking the regular resource call route.
==> default:  41:            declare_resource(method_symbol, args[0], caller[0], &block)
==> default:  42:          else
==> default:  43:            begin
==> default:  44:              super
==> default:  45:            rescue NoMethodError
==> default:  46>>             raise NoMethodError, "No resource or method named `#{method_symbol}' for #{describe_self_for_error}"
==> default:  47:            rescue NameError
==> default:  48:              raise NameError, "No resource, method, or local variable named `#{method_symbol}' for #{describe_self_for_error}"
==> default:  49:            end
==> default:  50:          end
==> default:  51:        end
==> default:  52:
==> default:  53:        def has_resource_definition?(name)
==> default:  54:          yes_or_no = run_context.definitions.has_key?(name)
==> default:  55:
==> default:
==> default: [2015-05-12T11:32:28-07:00] ERROR: Running exception handlers
==> default: [2015-05-12T11:32:28-07:00] ERROR: Exception handlers complete
==> default: [2015-05-12T11:32:28-07:00] FATAL: Stacktrace dumped to C:/var/chef/cache/chef-stacktrace.out
==> default: [2015-05-12T11:32:28-07:00] FATAL: NoMethodError: No resource or method named `iis_root' for `Chef::Recipe "foobar"'
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

What is the correct syntax for my wrapper cookbook? This is what I'm trying. 

```chef
iis_root 'defaultDocuments' do
  default_documents ['foobar.html']
end
```

I don't see any code on github referring to 'iis_root' or 'default_documents'

**Comment by spuder** [comment]
Ok finally got it.  I had to delete my berksfile.lock. 

I can confirm that all default documents exept for foobar.html are now present in IIS. This also appears to be idempotent. 

Ok to close.

**Comment by EasyAsABC123** [comment]
We'll leave it open until we merge the code into master.  Especially since this doesn't allow for sites or applications yet.

Justin Schuhmann

**Comment by EasyAsABC123** [comment]
testing latest worked for me, please verify

**Comment by spuder** [comment]
I accidentally used the old syntax, which surprisingly still worked. 

```
iis_root 'defaultDocuments' do
  default_documents ['docCent.aspx']
  action :add
end
```

I kill vagrant and ran again

```
iis_root 'defaultDocuments' do
  add_default_documents ['foobar.html']
  action :add
end

iis_root 'dmg' do
  delete_default_documents ['index.html']
  action :delete
end
```

Worked perfectly. 

I rebooted and ran again just to make sure it is idempotent. I did get an error starting one of the application pools, but I think that is unrelated.

I'd say this passes initial smoke tests!!!!

**Comment by EasyAsABC123** [comment]
I'll write up the documentation this weekend.  Then create a pull request.

Justin Schuhmann

**Comment by spuder** [comment]
Looks good, I added an example to the documentation

#184

**Comment by EasyAsABC123** [comment]
resolved by #195

**Comment by EasyAsABC123** [comment]
merged to master
